api_platform:
  # The title of the API.
  title: 'API title - my nice and great API -)'

  # The description of the API.
  description: 'API description - see upper'

  # The version of the API.
  version: '0.0.1'

  # Set this to false if you want Webby to disappear.
  show_webby: true

  mapping:
    paths:
      - '%kernel.project_dir%/src/Entity'           # default configuration for annotations
      - '%kernel.project_dir%/config/api_platform'  # yaml configuration files directory

  patch_formats:
    json: [ 'application/merge-patch+json' ]

  # manually set the docs URI
#  enable_swagger_ui: false
#  enable_re_doc: false

  swagger:
    versions: [ 3 ]
    api_keys:
      apiKey:
        name: Authorization
        type: header

  openapi:
    # The contact information for the exposed API.
    contact:
      # The identifying name of the contact person/organization.
      name: B2PWeb - eProtocole
      # The URL pointing to the contact information. MUST be in the format of a URL.
      url: http://b2pweb.com
      # The email address of the contact person/organization. MUST be in the format of an email address.
      email: fmohier@b2pweb.com
    # A URL to the Terms of Service for the API. MUST be in the format of a URL.
    termsOfService:
    # The license information for the exposed API.
    license:
      # The license name used for the API.
      name:
      # URL to the license used for the API. MUST be in the format of a URL.
      url: