doctrine:
  dbal:
    url: '%env(resolve:DATABASE_URL)%'

    #       Configure here if no DATABASE_URL exists in the environment!
    #        dbname:               database
    #        host:                 localhost
    #        port:                 1234
    #        user:                 user
    #        password:             secret
    #        driver:               pdo_mysql
    #
    # IMPORTANT: You MUST configure your server version,
    # either here or in the DATABASE_URL env var (see .env file)
    #server_version: '13'

    mapping_types:
      enum: string

    types:
      enum_address_type: App\DBAL\Types\AddressType
      enum_contact_type: App\DBAL\Types\ContactType
      enum_document_type: App\DBAL\Types\DocumentType
      enum_human_gender: App\DBAL\Types\HumanGenderType
      enum_language_type: App\DBAL\Types\LanguageType
      enum_relation_type: App\DBAL\Types\RelationType

  orm:
    auto_generate_proxy_classes: true
    naming_strategy: doctrine.orm.naming_strategy.underscore_number_aware
    auto_mapping: true
    mappings:
      App:
        is_bundle: false
        type: annotation
        dir: '%kernel.project_dir%/src/Entity'
        prefix: 'App\Entity'
        alias: App
      # stof/doctrine-extensions:
#      gedmo_translatable:
#        type: annotation
#        prefix: Gedmo\Translatable\Entity
#        dir: "%kernel.project_dir%/vendor/gedmo/doctrine-extensions/src/Translatable/Entity"
#        alias: GedmoTranslatable # (optional) it will default to the name set for the mapping
#        is_bundle: false
#      gedmo_translator:
#        type: annotation
#        prefix: Gedmo\Translator\Entity
#        dir: "%kernel.project_dir%/vendor/gedmo/doctrine-extensions/src/Translator/Entity"
#        alias: GedmoTranslator # (optional) it will default to the name set for the mapping
#        is_bundle: false
#      gedmo_loggable:
#        type: annotation
#        prefix: Gedmo\Loggable\Entity
#        dir: "%kernel.project_dir%/vendor/gedmo/doctrine-extensions/src/Loggable/Entity"
#        alias: GedmoLoggable # (optional) it will default to the name set for the mapping
#        is_bundle: false
#      gedmo_tree:
#        type: annotation
#        prefix: Gedmo\Tree\Entity
#        dir: "%kernel.project_dir%/vendor/gedmo/doctrine-extensions/src/Tree/Entity"
#        alias: GedmoTree # (optional) it will default to the name set for the mapping
#        is_bundle: false
