doctrine:
    dbal:
        url: '%env(resolve:DATABASE_URL)%'

#       Configure here if no DATABASE_URL exists in the environment!
#        dbname:               database
#        host:                 localhost
#        port:                 1234
#        user:                 user
#        password:             secret
#        driver:               pdo_mysql
#
        # IMPORTANT: You MUST configure your server version,
        # either here or in the DATABASE_URL env var (see .env file)
        #server_version: '13'
    orm:
        auto_generate_proxy_classes: true
        naming_strategy: doctrine.orm.naming_strategy.underscore_number_aware
        auto_mapping: true
        mappings:
            App:
                is_bundle: false
                type: annotation
                dir: '%kernel.project_dir%/src/Entity'
                prefix: 'App\Entity'
                alias: App
