nelmio_cors:
    defaults:
        allow_credentials: false
        allow_origin: [ '%env(CORS_ALLOW_ORIGIN)%' ]
        allow_methods: [ 'OPTIONS', 'GET', 'POST', 'PUT', 'PATCH', 'DELETE' ]
        allow_headers: [ 'Accept', 'Authorization', 'Content-Type', 'X-User-Agent' ]
        expose_headers: [ 'Link' ]
        max_age: 3600
        hosts: []
        origin_regex: false
        forced_allow_origin_value: ~
    paths:
        '^/api/':
            allow_origin: [ '*' ]
            allow_headers: [ 'Authorization', 'Content-Type', 'X-User-Agent' ]
            allow_methods: [ 'POST', 'PUT', 'GET', 'DELETE' ]
            max_age: 3600
        '^/':
            origin_regex: true
            allow_origin: [ '^http://localhost:[0-9]+' ]
            allow_headers: [ 'X-Custom-Auth' ]
            allow_methods: [ 'POST', 'PUT', 'GET', 'DELETE' ]
            max_age: 3600
            hosts: [ '^api.' ]
