version: "3.8"

services:

  # PHP interpreter
  php-fpm:
    build:
      context: docker/php-fpm
      args:
        - TAG_PHP=${TAG_PHP}
    image: ${PROJECT}_php:${PROJECT_VERSION}-${PROJECT_API_VERSION}
    container_name: ${PROJECT}_php-fpm
    restart: unless-stopped
    ports:
      - "8000:8000"
    volumes:
      - ./:/var/www/:rw
    environment:
      - APP_USER=${APP_USER}
      - APP_ENV=${APP_ENV}
      - APP_SECRET=${APP_SECRET}
      - DATABASE_URL=mysql://${DATABASE_USER}:${DATABASE_PASSWORD}@${DATABASE_HOST}:${DATABASE_PORT}/${DATABASE_NAME}?serverVersion=mariadb-${TAG_MARIADB}
    depends_on:
      - mariadb
    networks:
      - dev

  # API web server
  nginx-api:
    build:
      context: docker/nginx-api
      args:
        - TAG_NGINX=${TAG_NGINX}
        - VERSION=${PROJECT_API_VERSION}
    image: ${PROJECT}_api:${PROJECT_VERSION}-${PROJECT_API_VERSION}
    container_name: ${PROJECT}_nginx_api
    restart: unless-stopped
    ports:
      - "8001:80"
    volumes:
      - ./:/var/www/:rw
    depends_on:
      - php-fpm
    networks:
      - dev

  # Application database
  mariadb:
    build:
      context: docker/mariadb
      args:
        - TAG_MARIADB=${TAG_MARIADB}
    image: ${PROJECT}_db:${PROJECT_VERSION}-${PROJECT_API_VERSION}
    container_name: ${PROJECT}_mariadb
    labels:
      com.symfony.server.service-prefix: 'mariadb'
    restart: unless-stopped
    volumes:
      - db-data:/var/lib/mysql
    ports:
      - "3306:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=${DATABASE_ROOT_PASSWORD}
      - MYSQL_DATABASE=${DATABASE_NAME}
      - MYSQL_USER=${DATABASE_USER}
      - MYSQL_PASSWORD=${DATABASE_PASSWORD}
    networks:
      - dev

  # MySQL Web interface
  # Browse http://localhost:8080 to monitor the database
  phpmyadmin:
    build:
      context: docker/phpmyadmin
      args:
        - TAG_PHPMYADMIN=${TAG_PHPMYADMIN}
    image: ${PROJECT}_dbadmin:${PROJECT_VERSION}-${PROJECT_API_VERSION}
    container_name: ${PROJECT}_phpmyadmin
    restart: unless-stopped
    depends_on:
      - mariadb
    ports:
      - "8080:80"
    environment:
      - PMA_ARBITRARY=1
      - PMA_HOST=${DATABASE_HOST}
      - PMA_PORT=${DATABASE_PORT}
      - PMA_USER=root
      - PMA_PASSWORD=${DATABASE_ROOT_PASSWORD}
    networks:
      - dev

  # Catch mails sent from the PHP application
  # Browse http://localhost:1080 to view the webmail
  mailcatcher:
    build:
      context: docker/mailcatcher
      args:
        - TAG_MAILCATCHER=${TAG_MAILCATCHER}
    image: ${PROJECT}_mailer:${PROJECT_VERSION}-${PROJECT_API_VERSION}
    container_name: ${PROJECT}_mailcatcher
    labels:
      com.symfony.server.service-prefix: 'MAILER'
    restart: unless-stopped
    ports:
      - "1025:1025"
      - "1080:1080"
    networks:
      - dev

  # Front UI web server
  nginx-ui:
    build:
      context: docker/nginx-ui
      args:
        - TAG_NGINX=${TAG_NGINX}
        - VERSION=${PROJECT_PWA_VERSION}
    image: ${PROJECT}_pwa:${PROJECT_VERSION}-${PROJECT_PWA_VERSION}
    container_name: ${PROJECT}_nginx_ui
    restart: unless-stopped
    ports:
      - "8002:80"
    volumes:
      - ./src_ui:/var/www/:rw
    networks:
      - dev

networks:
  dev:

volumes:
  db-data:
