api_platform:
    resource: .
    type: api_platform
    prefix: /api
    # Default configuration
    defaults:
        path_segment_name_generator: api_platform.path_segment_name_generator.underscore
    #    path_segment_name_generator: api_platform.path_segment_name_generator.dash
