monolog:
  channels:
    - audit
    - requests
    - application

  handlers:
    main:
      type: stream
      path: "%kernel.logs_dir%/%kernel.environment%.log"
      level: debug
      # Exclude kernel events and doctrine/requests tracking
      channels: [ "!event","!doctrine","!requests" ]
    requests:
      type: stream
      path: "%kernel.logs_dir%/%kernel.environment%.requests.log"
      level: debug
      # Only requests
      channels: [ "requests" ]
    # uncomment to get logging in your browser
    # you may have to allow bigger header sizes in your Web server configuration
    #firephp:
    #    type: firephp
    #    level: info
    #chromephp:
    #    type: chromephp
    #    level: info
    console:
      type: console
      process_psr_3_messages: false
      channels: [ "!event", "!doctrine", "!console" ]
