security:
  password_hashers:
    # Use your user class name here
    App\Entity\User:
      algorithm: bcrypt # This should be the same value as in config/packages/security.yaml
      cost: 4           # Lowest possible value for bcrypt
      time_cost: 3      # Lowest possible value for argon
      memory_cost: 10   # Lowest possible value for argon
