#!/bin/sh
set -eux

echo "Configuring nginx (hostname: ${HOSTNAME})..."

# Create user if necessary
if ! getent passwd "${APP_USER}"; then
    useradd --uid "${APP_USER}" --create-home dev
fi

# Initialize DOCKER_NETWORKS
export DOCKER_NETWORKS=$(ip -o -f inet addr show | awk '/scope global/ {print $4}' | paste -sd "," -)

# Use APP_USER as php-fpm user and fix permissions
sed --expression "s/www-data/${APP_USER}/g" --in-place /etc/php/*/fpm/php-fpm.d/docker.conf
chown -R "${APP_USER}:${APP_USER}" var public

# Configure application
if [ "${APP_ENV}" = "prod" ]; then
    if [ -f vendor/bin/phpcov ]
    then
        # Remove phpcov tool
        rm vendor/bin/phpcov
    fi

    # Generate cache
    until gosu "${APP_USER}:${APP_USER}" composer install --classmap-authoritative --no-dev --no-interaction --no-progress --no-suggest --optimize-autoloader --prefer-dist ; do
        sleep 5
    done
else
    # Generate cache
    until gosu "${APP_USER}:${APP_USER}" composer install --no-interaction --no-progress --no-suggest --prefer-dist ; do
        sleep 5
    done

    # Enable PHP PCOV extension
    phpenmod pcov
fi

# Install assets
gosu "${APP_USER}:${APP_USER}" bin/console assets:install

echo "Done!"

# Run command
exec "$@"
